repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0  # 0.22.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.24 # v0.1.20
    hooks:
      - id: shellcheck
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.43.0 # v0.39.0
    hooks:
      - id: markdownlint
