#pragma once
#include <esp_event.h>

ESP_EVENT_DECLARE_BASE(UPDATEMANAGER_EVENT);

enum updatemanager_event_t {
  NEXTION_UPDATE_STARTED,
  NEXTION_UPDATE_FINISHED,
  NEXTION_UPDATE_PROGRESS,
  FIRMWARE_UPDATE_STARTED,
  FIRMWARE_UPDATE_FINISHED,
  FIRMWARE_UPDATE_PROGRESS,
  LITTLEFS_UPDATE_STARTED,
  LITTLEFS_UPDATE_FINISHED,
  LITTLEFS_UPDATE_PROGRESS,
};