/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: protobuf_nspanel_entity.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "protobuf_nspanel_entity.pb-c.h"
void   nspanel_entity_state__light__init
                     (NSPanelEntityState__Light         *message)
{
  static const NSPanelEntityState__Light init_value = NSPANEL_ENTITY_STATE__LIGHT__INIT;
  *message = init_value;
}
void   nspanel_entity_state__init
                     (NSPanelEntityState         *message)
{
  static const NSPanelEntityState init_value = NSPANEL_ENTITY_STATE__INIT;
  *message = init_value;
}
size_t nspanel_entity_state__get_packed_size
                     (const NSPanelEntityState *message)
{
  assert(message->base.descriptor == &nspanel_entity_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t nspanel_entity_state__pack
                     (const NSPanelEntityState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &nspanel_entity_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t nspanel_entity_state__pack_to_buffer
                     (const NSPanelEntityState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &nspanel_entity_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
NSPanelEntityState *
       nspanel_entity_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (NSPanelEntityState *)
     protobuf_c_message_unpack (&nspanel_entity_state__descriptor,
                                allocator, len, data);
}
void   nspanel_entity_state__free_unpacked
                     (NSPanelEntityState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &nspanel_entity_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor nspanel_entity_state__light__field_descriptors[7] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(NSPanelEntityState__Light, type),
    &nspanel_entity_state__entity_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "brightness",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelEntityState__Light, brightness),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color_temp",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelEntityState__Light, color_temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hue",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelEntityState__Light, hue),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "saturation",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(NSPanelEntityState__Light, saturation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "can_color_temp",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(NSPanelEntityState__Light, can_color_temp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "can_color",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(NSPanelEntityState__Light, can_color),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nspanel_entity_state__light__field_indices_by_name[] = {
  1,   /* field[1] = brightness */
  6,   /* field[6] = can_color */
  5,   /* field[5] = can_color_temp */
  2,   /* field[2] = color_temp */
  3,   /* field[3] = hue */
  4,   /* field[4] = saturation */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange nspanel_entity_state__light__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor nspanel_entity_state__light__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NSPanelEntityState.Light",
  "Light",
  "NSPanelEntityState__Light",
  "",
  sizeof(NSPanelEntityState__Light),
  7,
  nspanel_entity_state__light__field_descriptors,
  nspanel_entity_state__light__field_indices_by_name,
  1,  nspanel_entity_state__light__number_ranges,
  (ProtobufCMessageInit) nspanel_entity_state__light__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue nspanel_entity_state__entity_type__enum_values_by_number[1] =
{
  { "LIGHT", "NSPANEL_ENTITY_STATE__ENTITY_TYPE__LIGHT", 0 },
};
static const ProtobufCIntRange nspanel_entity_state__entity_type__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex nspanel_entity_state__entity_type__enum_values_by_name[1] =
{
  { "LIGHT", 0 },
};
const ProtobufCEnumDescriptor nspanel_entity_state__entity_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "NSPanelEntityState.EntityType",
  "EntityType",
  "NSPanelEntityState__EntityType",
  "",
  1,
  nspanel_entity_state__entity_type__enum_values_by_number,
  1,
  nspanel_entity_state__entity_type__enum_values_by_name,
  1,
  nspanel_entity_state__entity_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor nspanel_entity_state__field_descriptors[1] =
{
  {
    "light",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(NSPanelEntityState, entity_case),
    offsetof(NSPanelEntityState, light),
    &nspanel_entity_state__light__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned nspanel_entity_state__field_indices_by_name[] = {
  0,   /* field[0] = light */
};
static const ProtobufCIntRange nspanel_entity_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor nspanel_entity_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "NSPanelEntityState",
  "NSPanelEntityState",
  "NSPanelEntityState",
  "",
  sizeof(NSPanelEntityState),
  1,
  nspanel_entity_state__field_descriptors,
  nspanel_entity_state__field_indices_by_name,
  1,  nspanel_entity_state__number_ranges,
  (ProtobufCMessageInit) nspanel_entity_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
