; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_flags = 
	-Iinclude
	-Ilib/ProtoBuf

[env:original_sonoff]
platform = espressif32@6.12.0
board = esp32doit-devkit-v1
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
lib_deps = https://github.com/joltwallet/esp_littlefs.git#v1.19.2
build_flags = 
	${env.build_flags}
	-DBOARD_SONOFF

[env:custom_pcb]
platform = espressif32@6.12.0
board = 4d_systems_esp32s3_gen4_r8n16
framework = espidf
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
lib_deps = https://github.com/joltwallet/esp_littlefs.git#v1.19.2
build_flags = 
	${env.build_flags}
	-DBOARD_CUSTOM
